-- NOTE (2026-03-29): This file was split into per-dataset bootstraps.
-- Run the one you need from `supabase/`:
-- - `bootstrap.dev.sql`  -> creates `soccer_zone_dev`
-- - `bootstrap.test.sql` -> creates `soccer_zone_test`
-- - `bootstrap.prod.sql` -> creates `soccer_zone_prod`
